#1~~> verificar sintaxe
#docker-compose build

#2~~> fazer um teste
#docker-compose up

#3~~> desfazer a operação
#docker-compose down

#Defino a versão a ser utilizado do docker-compose
version: "3"

#Defino o volume que irá ser utilizado pelos container.
#Definimos um volume chamado ~~> produtosdata
volumes:
      produtosdata:

#Defino as minhas redes
networks:
       frontend:
       backend:

#Define os contêneires que serão utilizados ~~> Imagens, contextos, etc.
services:

      mysql:
        image: "mysql:5.7"
        volumes:
          - produtosdata:/var/lib/mysql
          #- ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
        networks:
          - backend
        environment:
          - MYSQL_ROOT_PASSWORD=numsey
          - bind-address=0.0.0.0
      
      #mvc:
      #  build :
      #   context : .
      #   dockerfile : Dockerfile
      #  networks :
      #   - backend 
      #   - frontend
      #  ports:
      #   - 5000:80
      #  environment :
      #   - DBHOST=mysql
      #   - ASPNETCORE_ENVIRONMENT=Development
      #  depends_on :
      #   - mysql   